version: '3.9'

services:
  nodejs_login_tracker:
    container_name: login_tracker_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgsql_db
    ports:
    - "5000:5000"

  pgsql_db:
    container_name: login_tracker_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=auth_tracker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: